server:
  port: 8760

spring:
  application:
    name: service-registry

eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: false #This makes it not call itself as a client
      fetch-registry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
