server:
  port: 8400

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: project-microservice
          uri: lb://project-microservice
          predicates:
            - Path=/project/**
        - id: task-microservice
          uri: lb://task-microservice
          predicates:
            - Path=/task/**
